function [acc, MC] = clasificador(X, Y, reglas, conjuntos)
    numEjemplos = size(X, 1);
    predicciones = zeros(1, numEjemplos);
    for i = 1:numEjemplos
        predicciones(i) = clasificacion( ...
            gradoAsociacionPorClases( ...
                gradoAsociacion( ...
                    reglas, ...
                    gradoCompatibilidad( ...
                        X(i,1:4), ...
                        reglas, ...
                        conjuntos ...
                    ) ...
                ), ...
                reglas ...
            ) ...
        );
    end
    acc = sum(predicciones == Y) / numEjemplos;
    MC = confusionmat(Y, predicciones);
    disp(acc);
    disp(MC);
end